/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_WAYPOINTSERVERSTUB_H_
#define JSONRPC_CPP_STUB_WAYPOINTSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class waypointserverstub : public jsonrpc::AbstractServer<waypointserverstub>
{
    public:
        waypointserverstub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<waypointserverstub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("saveToFile", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN,  NULL), &waypointserverstub::saveToFileI);
            this->bindAndAddMethod(jsonrpc::Procedure("restoreFromFile", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN,  NULL), &waypointserverstub::restoreFromFileI);
            this->bindAndAddMethod(jsonrpc::Procedure("add", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_OBJECT, NULL), &waypointserverstub::addI);
            this->bindAndAddMethod(jsonrpc::Procedure("remove", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &waypointserverstub::removeI);
            this->bindAndAddMethod(jsonrpc::Procedure("get", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT, "param1",jsonrpc::JSON_STRING, NULL), &waypointserverstub::getI);
            this->bindAndAddMethod(jsonrpc::Procedure("getNames", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_ARRAY,  NULL), &waypointserverstub::getNamesI);
            this->bindAndAddMethod(jsonrpc::Procedure("distanceAndBearing", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &waypointserverstub::distanceAndBearingI);
            this->bindAndAddMethod(jsonrpc::Procedure("updateWaypoint", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING,"param3",jsonrpc::JSON_STRING,"param4",jsonrpc::JSON_STRING,"param5",jsonrpc::JSON_STRING, NULL), &waypointserverstub::updateWaypointI);
            this->bindAndAddMethod(jsonrpc::Procedure("addNew", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING,"param3",jsonrpc::JSON_STRING,"param4",jsonrpc::JSON_STRING,"param5",jsonrpc::JSON_STRING, NULL), &waypointserverstub::addNewI);
        }

        inline virtual void saveToFileI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->saveToFile();
        }
        inline virtual void restoreFromFileI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->restoreFromFile();
        }
        inline virtual void addI(const Json::Value &request, Json::Value &response)
        {
            response = this->add(request[0u]);
        }
        inline virtual void removeI(const Json::Value &request, Json::Value &response)
        {
            response = this->remove(request[0u].asString());
        }
        inline virtual void getI(const Json::Value &request, Json::Value &response)
        {
            response = this->get(request[0u].asString());
        }
        inline virtual void getNamesI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getNames();
        }
        inline virtual void distanceAndBearingI(const Json::Value &request, Json::Value &response)
        {
            response = this->distanceAndBearing(request[0u].asString(), request[1u].asString());
        }
        inline virtual void updateWaypointI(const Json::Value &request, Json::Value &response)
        {
            response = this->updateWaypoint(request[0u].asString(), request[1u].asString(), request[2u].asString(), request[3u].asString(), request[4u].asString());
        }
        inline virtual void addNewI(const Json::Value &request, Json::Value &response)
        {
            response = this->addNew(request[0u].asString(), request[1u].asString(), request[2u].asString(), request[3u].asString(), request[4u].asString());
        }
        virtual bool saveToFile() = 0;
        virtual bool restoreFromFile() = 0;
        virtual bool add(const Json::Value& param1) = 0;
        virtual bool remove(const std::string& param1) = 0;
        virtual Json::Value get(const std::string& param1) = 0;
        virtual Json::Value getNames() = 0;
        virtual std::string distanceAndBearing(const std::string& param1, const std::string& param2) = 0;
        virtual bool updateWaypoint(const std::string& param1, const std::string& param2, const std::string& param3, const std::string& param4, const std::string& param5) = 0;
        virtual bool addNew(const std::string& param1, const std::string& param2, const std::string& param3, const std::string& param4, const std::string& param5) = 0;
};

#endif //JSONRPC_CPP_STUB_WAYPOINTSERVERSTUB_H_
